"""Domain enums."""

from enum import Enum


class MissionStatus(str, Enum):
    """Lifecycle states for a mission."""

    CREATED = "CREATED"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class ExecutionState(str, Enum):
    """Worker/dispatch state, distinct from mission lifecycle."""

    QUEUED = "QUEUED"
    CLAIMED = "CLAIMED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    EXHAUSTED = "EXHAUSTED"


class StepStatus(str, Enum):
    """Lifecycle states for a plan step."""

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AgentPhase(str, Enum):
    """Operational phase of the agent loop / supervisor."""

    UNDERSTANDING = "UNDERSTANDING"
    PLANNING = "PLANNING"
    SELECTING = "SELECTING"
    DELEGATING = "DELEGATING"
    TOOL_EXECUTION = "TOOL_EXECUTION"
    OBSERVING = "OBSERVING"
    REASONING = "REASONING"
    ADAPTING = "ADAPTING"
    ACTING = "ACTING"
    VERIFYING = "VERIFYING"
    SYNTHESIZING = "SYNTHESIZING"
    COMPLETING = "COMPLETING"


class AgentRole(str, Enum):
    """Specialist roles in the autonomous operations layer."""

    SUPERVISOR = "SUPERVISOR"
    DATA_ANALYST = "DATA_ANALYST"
    INVESTIGATOR = "INVESTIGATOR"
    REPORTER = "REPORTER"
    REMEDIATOR = "REMEDIATOR"


class EventType(str, Enum):
    """Types of mission events."""

    MISSION_CREATED = "MISSION_CREATED"
    MISSION_QUEUED = "MISSION_QUEUED"
    MISSION_CLAIMED = "MISSION_CLAIMED"
    LEASE_EXPIRED = "LEASE_EXPIRED"
    MISSION_RECOVERED = "MISSION_RECOVERED"
    ATTEMPT_FAILED = "ATTEMPT_FAILED"
    EXECUTION_EXHAUSTED = "EXECUTION_EXHAUSTED"
    PLANNING_STARTED = "PLANNING_STARTED"
    EXECUTION_PLAN_GENERATED = "EXECUTION_PLAN_GENERATED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    STEP_STARTED = "STEP_STARTED"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_FAILED = "STEP_FAILED"
    INVESTIGATION_STARTED = "INVESTIGATION_STARTED"
    DATASET_PROFILE_COMPLETED = "DATASET_PROFILE_COMPLETED"
    MISSING_DATA_ANALYSIS_COMPLETED = "MISSING_DATA_ANALYSIS_COMPLETED"
    DUPLICATE_ANALYSIS_COMPLETED = "DUPLICATE_ANALYSIS_COMPLETED"
    TYPE_FORMAT_ANALYSIS_COMPLETED = "TYPE_FORMAT_ANALYSIS_COMPLETED"
    OUTLIER_ANALYSIS_COMPLETED = "OUTLIER_ANALYSIS_COMPLETED"
    CONSISTENCY_ANALYSIS_COMPLETED = "CONSISTENCY_ANALYSIS_COMPLETED"
    FINDINGS_PRIORITIZED = "FINDINGS_PRIORITIZED"
    FINAL_REPORT_GENERATED = "FINAL_REPORT_GENERATED"
    MISSION_UNDERSTOOD = "MISSION_UNDERSTOOD"
    DELEGATION_PLAN_CREATED = "DELEGATION_PLAN_CREATED"
    TASK_DELEGATED = "TASK_DELEGATED"
    AGENT_STARTED = "AGENT_STARTED"
    AGENT_COMPLETED = "AGENT_COMPLETED"
    AGENT_FAILED = "AGENT_FAILED"
    SUPERVISOR_OBSERVED = "SUPERVISOR_OBSERVED"
    REPLAN_TRIGGERED = "REPLAN_TRIGGERED"
    TASK_SKIPPED = "TASK_SKIPPED"
    SYNTHESIS_STARTED = "SYNTHESIS_STARTED"
    SYNTHESIS_COMPLETED = "SYNTHESIS_COMPLETED"
    ACTION_PROPOSED = "ACTION_PROPOSED"
    ACTION_AUTHORIZED = "ACTION_AUTHORIZED"
    ACTION_STARTED = "ACTION_STARTED"
    ACTION_COMPLETED = "ACTION_COMPLETED"
    ACTION_FAILED = "ACTION_FAILED"
    ACTION_VERIFIED = "ACTION_VERIFIED"
    ACTION_VERIFICATION_FAILED = "ACTION_VERIFICATION_FAILED"
    WORKING_COPY_CREATED = "WORKING_COPY_CREATED"
    WORKING_COPY_UPDATED = "WORKING_COPY_UPDATED"
    REPLAN_AFTER_ACTION = "REPLAN_AFTER_ACTION"
    AGENT_PLAN_CREATED = "AGENT_PLAN_CREATED"
    TOOL_SELECTED = "TOOL_SELECTED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    EVIDENCE_RECEIVED = "EVIDENCE_RECEIVED"
    AGENT_DECISION = "AGENT_DECISION"
    ADAPTIVE_INVESTIGATION_TRIGGERED = "ADAPTIVE_INVESTIGATION_TRIGGERED"
    AGENT_LOOP_LIMIT_REACHED = "AGENT_LOOP_LIMIT_REACHED"
    MODEL_REASONING_STARTED = "MODEL_REASONING_STARTED"
    MODEL_DECISION_RECEIVED = "MODEL_DECISION_RECEIVED"
    MODEL_DECISION_VALIDATED = "MODEL_DECISION_VALIDATED"
    MODEL_DECISION_REJECTED = "MODEL_DECISION_REJECTED"
    SPECIALIST_DELEGATED = "SPECIALIST_DELEGATED"
    OBSERVATION_REQUESTED = "OBSERVATION_REQUESTED"
    MODEL_REPLANNED = "MODEL_REPLANNED"
    MODEL_COMPLETED = "MODEL_COMPLETED"
    EXTERNAL_TOOL_PROPOSED = "EXTERNAL_TOOL_PROPOSED"
    EXTERNAL_TOOL_AUTHORIZED = "EXTERNAL_TOOL_AUTHORIZED"
    EXTERNAL_TOOL_STARTED = "EXTERNAL_TOOL_STARTED"
    EXTERNAL_TOOL_COMPLETED = "EXTERNAL_TOOL_COMPLETED"
    EXTERNAL_TOOL_FAILED = "EXTERNAL_TOOL_FAILED"
    EXTERNAL_TOOL_REJECTED = "EXTERNAL_TOOL_REJECTED"
    MEMORY_EXTRACTION_STARTED = "MEMORY_EXTRACTION_STARTED"
    MEMORY_EXTRACTED = "MEMORY_EXTRACTED"
    MEMORY_MERGED = "MEMORY_MERGED"
    MEMORY_REJECTED = "MEMORY_REJECTED"
    MEMORY_EXTRACTION_FAILED = "MEMORY_EXTRACTION_FAILED"
    FINAL_REASONING_COMPLETED = "FINAL_REASONING_COMPLETED"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    MISSION_FAILED = "MISSION_FAILED"


class ModelDecisionKind(str, Enum):
    """Explicit supervisor decisions. Not free-form prose."""

    DELEGATE = "DELEGATE"
    OBSERVE = "OBSERVE"
    ACTION = "ACTION"
    EXTERNAL = "EXTERNAL"
    COMPLETE = "COMPLETE"


class PlannerSource(str, Enum):
    """Identifies which planner produced a plan."""

    GEMINI_ADK = "GEMINI_ADK"
    LOCAL_FALLBACK = "LOCAL_FALLBACK"


class FindingCategory(str, Enum):
    """Investigation finding categories."""

    MISSING_DATA = "MISSING_DATA"
    DUPLICATE_ROWS = "DUPLICATE_ROWS"
    TYPE_FORMAT_ANOMALY = "TYPE_FORMAT_ANOMALY"
    CATEGORICAL_INCONSISTENCY = "CATEGORICAL_INCONSISTENCY"
    NUMERIC_OUTLIER = "NUMERIC_OUTLIER"
    CONSISTENCY_VIOLATION = "CONSISTENCY_VIOLATION"


class ActionStatus(str, Enum):
    """Lifecycle of a controlled remediation action."""

    PROPOSED = "PROPOSED"
    AUTHORIZED = "AUTHORIZED"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    VERIFIED = "VERIFIED"
    VERIFICATION_FAILED = "VERIFICATION_FAILED"


class EvidenceSourceType(str, Enum):
    """Where an evidence record came from. External pages are never dataset facts."""

    DATASET = "DATASET"
    EXTERNAL = "EXTERNAL"
    ACTION = "ACTION"


class ExternalInvocationStatus(str, Enum):
    """Lifecycle of a registered external-tool call."""

    PROPOSED = "PROPOSED"
    AUTHORIZED = "AUTHORIZED"
    RUNNING = "RUNNING"
    SUCCEEDED = "SUCCEEDED"
    FAILED = "FAILED"
    REJECTED = "REJECTED"


class MemoryType(str, Enum):
    """Explicit memory categories. Not a dump of mission transcripts."""

    FACT = "FACT"
    PROCEDURE = "PROCEDURE"
    INSIGHT = "INSIGHT"
    PREFERENCE = "PREFERENCE"


class MemoryScope(str, Enum):
    """Where a memory may be reused."""

    MISSION = "MISSION"
    DATASET = "DATASET"
    GLOBAL = "GLOBAL"


class MemoryExtractionSource(str, Enum):
    """Who proposed the memory. Persistence is always ATLAS."""

    LOCAL_FALLBACK = "LOCAL_FALLBACK"
    GEMINI_ADK = "GEMINI_ADK"
    DETERMINISTIC_EVIDENCE = "DETERMINISTIC_EVIDENCE"


class ExternalAuthorizationMode(str, Enum):
    """How a registered external tool may be authorized today."""

    AUTOMATIC = "AUTOMATIC"
    DISABLED = "DISABLED"


class ActionRisk(str, Enum):
    """Declared risk of an allowlisted action."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class Severity(str, Enum):
    """Finding severity derived from evidence."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
