"""Domain enums."""

from enum import Enum


class MissionStatus(str, Enum):
    """Lifecycle states for a mission."""

    CREATED = "CREATED"
    PLANNING = "PLANNING"
    EXECUTING = "EXECUTING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class StepStatus(str, Enum):
    """Lifecycle states for a plan step."""

    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"


class AgentPhase(str, Enum):
    """Operational phase of the agent loop."""

    UNDERSTANDING = "UNDERSTANDING"
    PLANNING = "PLANNING"
    SELECTING = "SELECTING"
    TOOL_EXECUTION = "TOOL_EXECUTION"
    OBSERVING = "OBSERVING"
    REASONING = "REASONING"
    ADAPTING = "ADAPTING"
    COMPLETING = "COMPLETING"


class EventType(str, Enum):
    """Types of mission events."""

    MISSION_CREATED = "MISSION_CREATED"
    PLANNING_STARTED = "PLANNING_STARTED"
    EXECUTION_PLAN_GENERATED = "EXECUTION_PLAN_GENERATED"
    EXECUTION_STARTED = "EXECUTION_STARTED"
    STEP_STARTED = "STEP_STARTED"
    STEP_COMPLETED = "STEP_COMPLETED"
    STEP_FAILED = "STEP_FAILED"
    INVESTIGATION_STARTED = "INVESTIGATION_STARTED"
    DATASET_PROFILE_COMPLETED = "DATASET_PROFILE_COMPLETED"
    MISSING_DATA_ANALYSIS_COMPLETED = "MISSING_DATA_ANALYSIS_COMPLETED"
    DUPLICATE_ANALYSIS_COMPLETED = "DUPLICATE_ANALYSIS_COMPLETED"
    TYPE_FORMAT_ANALYSIS_COMPLETED = "TYPE_FORMAT_ANALYSIS_COMPLETED"
    OUTLIER_ANALYSIS_COMPLETED = "OUTLIER_ANALYSIS_COMPLETED"
    CONSISTENCY_ANALYSIS_COMPLETED = "CONSISTENCY_ANALYSIS_COMPLETED"
    FINDINGS_PRIORITIZED = "FINDINGS_PRIORITIZED"
    FINAL_REPORT_GENERATED = "FINAL_REPORT_GENERATED"
    MISSION_UNDERSTOOD = "MISSION_UNDERSTOOD"
    AGENT_PLAN_CREATED = "AGENT_PLAN_CREATED"
    TOOL_SELECTED = "TOOL_SELECTED"
    TOOL_STARTED = "TOOL_STARTED"
    TOOL_COMPLETED = "TOOL_COMPLETED"
    TOOL_FAILED = "TOOL_FAILED"
    EVIDENCE_RECEIVED = "EVIDENCE_RECEIVED"
    AGENT_DECISION = "AGENT_DECISION"
    ADAPTIVE_INVESTIGATION_TRIGGERED = "ADAPTIVE_INVESTIGATION_TRIGGERED"
    AGENT_LOOP_LIMIT_REACHED = "AGENT_LOOP_LIMIT_REACHED"
    FINAL_REASONING_COMPLETED = "FINAL_REASONING_COMPLETED"
    MISSION_COMPLETED = "MISSION_COMPLETED"
    MISSION_FAILED = "MISSION_FAILED"


class PlannerSource(str, Enum):
    """Identifies which planner produced a plan."""

    GEMINI_ADK = "GEMINI_ADK"
    LOCAL_FALLBACK = "LOCAL_FALLBACK"


class FindingCategory(str, Enum):
    """Investigation finding categories."""

    MISSING_DATA = "MISSING_DATA"
    DUPLICATE_ROWS = "DUPLICATE_ROWS"
    TYPE_FORMAT_ANOMALY = "TYPE_FORMAT_ANOMALY"
    CATEGORICAL_INCONSISTENCY = "CATEGORICAL_INCONSISTENCY"
    NUMERIC_OUTLIER = "NUMERIC_OUTLIER"
    CONSISTENCY_VIOLATION = "CONSISTENCY_VIOLATION"


class Severity(str, Enum):
    """Finding severity derived from evidence."""

    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"
