"""Domain models."""

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from atlas.domain.enums import (
    AgentPhase,
    AgentRole,
    EventType,
    ExecutionState,
    FindingCategory,
    MissionStatus,
    PlannerSource,
    Severity,
    StepStatus,
)


def utc_now() -> datetime:
    """Return current UTC timestamp."""
    return datetime.now(timezone.utc)


class PlanStep(BaseModel):
    """A single step in an execution plan."""

    id: str
    title: str
    description: str
    status: StepStatus = StepStatus.PENDING
    result: str | None = None
    error: str | None = None


class ExecutionPlan(BaseModel):
    """Structured plan generated by the planner."""

    steps: list[PlanStep]
    planner_source: PlannerSource
    summary: str | None = None


class NumericStats(BaseModel):
    """Basic statistics for a numeric column."""

    min: float
    max: float
    mean: float
    median: float
    std: float | None = None


class ColumnProfile(BaseModel):
    """Profile of a single dataset column."""

    name: str
    inferred_type: str
    non_null_count: int
    null_count: int
    null_percent: float
    unique_count: int
    numeric_stats: NumericStats | None = None


class DatasetProfile(BaseModel):
    """Deterministic profile of an inspected CSV."""

    row_count: int
    column_count: int
    columns: list[ColumnProfile]


class Finding(BaseModel):
    """A structured, evidence-based investigation finding."""

    finding_id: str
    category: FindingCategory
    title: str
    description: str
    affected_columns: list[str] = Field(default_factory=list)
    evidence: dict[str, Any] = Field(default_factory=dict)
    affected_row_count: int | None = None
    affected_row_percent: float | None = None
    severity: Severity
    priority: int = 0
    suggested_action: str
    detection_method: str


class RecommendedAction(BaseModel):
    """A recommended remediation action derived from findings."""

    action_id: str
    title: str
    description: str
    related_finding_ids: list[str] = Field(default_factory=list)
    priority: int = 0


class DatasetSummary(BaseModel):
    """Dataset snapshot included in the investigation report."""

    dataset_id: str | None = None
    original_filename: str | None = None
    row_count: int
    column_count: int
    columns: list[ColumnProfile]


class InvestigationReport(BaseModel):
    """Structured final report for a dataset investigation mission."""

    mission_summary: str
    dataset_summary: DatasetSummary
    investigation_summary: str
    findings: list[Finding]
    recommended_actions: list[RecommendedAction]
    overall_assessment: str
    reasoning_source: PlannerSource
    interpretations: list["AgentInterpretation"] = Field(default_factory=list)
    evidence_records: list["EvidenceRecord"] = Field(default_factory=list)


class AgentTask(BaseModel):
    """A single tool-backed task in the agent plan."""

    task_id: str
    tool_name: str
    objective: str
    depends_on: list[str] = Field(default_factory=list)
    status: StepStatus = StepStatus.PENDING
    adaptive: bool = False
    arguments: dict[str, Any] = Field(default_factory=dict)
    evidence_id: str | None = None
    result_summary: str | None = None
    decision_reason: str | None = None


class AgentPlan(BaseModel):
    """Inspectable structured plan of what ATLAS intends to do."""

    objective: str
    source: PlannerSource
    selected_tools: list[str]
    tasks: list[AgentTask] = Field(default_factory=list)
    status: str = "PENDING"
    current_task_id: str | None = None
    iteration: int = 0
    max_iterations: int = 12
    tool_call_count: int = 0

    def to_execution_plan(self) -> ExecutionPlan:
        """Project the agent plan onto the Round 1 execution-plan schema."""
        steps = [
            PlanStep(
                id=task.task_id,
                title=task.tool_name,
                description=task.objective,
                status=task.status,
                result=task.result_summary,
            )
            for task in self.tasks
        ]
        return ExecutionPlan(
            steps=steps,
            planner_source=self.source,
            summary=self.objective,
        )


class AgentDescriptor(BaseModel):
    """Identity and authorized capabilities of a specialist agent."""

    id: str
    name: str
    role: AgentRole
    description: str
    capabilities: list[str] = Field(default_factory=list)
    allowed_tools: list[str] = Field(default_factory=list)


class SpecialistFollowUp(BaseModel):
    """Evidence-driven work a specialist recommends to the supervisor."""

    capability: str
    objective: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    critical: bool = False
    reason: str = ""


class SpecialistTaskResult(BaseModel):
    """Structured result of a specialist task. Not a raw object dump."""

    summary: str
    finding_ids: list[str] = Field(default_factory=list)
    evidence_ids: list[str] = Field(default_factory=list)
    follow_ups: list[SpecialistFollowUp] = Field(default_factory=list)
    notes: str | None = None
    provenance: PlannerSource = PlannerSource.LOCAL_FALLBACK


class SpecialistTask(BaseModel):
    """First-class delegated work item assigned to a specialist agent."""

    task_id: str = Field(default_factory=lambda: str(uuid4()))
    mission_id: str
    agent_id: str
    objective: str
    capability: str
    inputs: dict[str, Any] = Field(default_factory=dict)
    depends_on: list[str] = Field(default_factory=list)
    status: StepStatus = StepStatus.PENDING
    critical: bool = False
    attempt_count: int = 0
    max_attempts: int = 2
    created_at: datetime = Field(default_factory=utc_now)
    started_at: datetime | None = None
    completed_at: datetime | None = None
    result: SpecialistTaskResult | None = None
    error: str | None = None
    evidence_ids: list[str] = Field(default_factory=list)


class DelegationPlan(BaseModel):
    """Supervisor-owned plan of specialist work. Persisted with the mission."""

    objective: str
    source: PlannerSource
    status: str = "IN_PROGRESS"
    tasks: list[SpecialistTask] = Field(default_factory=list)
    wave: int = 0
    replan_count: int = 0
    current_task_ids: list[str] = Field(default_factory=list)


class ToolInvocation(BaseModel):
    """A recorded tool call for mission observability."""

    invocation_id: str = Field(default_factory=lambda: str(uuid4()))
    tool_name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    status: StepStatus = StepStatus.PENDING
    evidence_id: str | None = None
    error: str | None = None
    adaptive: bool = False
    started_at: datetime = Field(default_factory=utc_now)
    completed_at: datetime | None = None


class EvidenceRecord(BaseModel):
    """Observed facts produced by a tool. Not agent interpretation."""

    evidence_id: str = Field(default_factory=lambda: str(uuid4()))
    tool_name: str
    task_id: str | None = None
    observed_facts: dict[str, Any] = Field(default_factory=dict)
    finding_ids: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)


class AgentInterpretation(BaseModel):
    """Agent reasoning about measured evidence. Must not invent metrics."""

    interpretation_id: str = Field(default_factory=lambda: str(uuid4()))
    kind: str
    text: str
    related_evidence_ids: list[str] = Field(default_factory=list)
    related_finding_ids: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)


class DatasetRecord(BaseModel):
    """Persisted metadata for an uploaded dataset."""

    dataset_id: str = Field(default_factory=lambda: str(uuid4()))
    original_filename: str
    stored_filename: str
    content_type: str
    size_bytes: int
    created_at: datetime = Field(default_factory=utc_now)


class DatasetUploadResponse(BaseModel):
    """Response after a successful dataset upload."""

    dataset_id: str
    original_filename: str
    stored_filename: str
    content_type: str
    size_bytes: int
    created_at: datetime

    @classmethod
    def from_record(cls, record: DatasetRecord) -> "DatasetUploadResponse":
        return cls(
            dataset_id=record.dataset_id,
            original_filename=record.original_filename,
            stored_filename=record.stored_filename,
            content_type=record.content_type,
            size_bytes=record.size_bytes,
            created_at=record.created_at,
        )


class MissionEvent(BaseModel):
    """An event recorded during mission execution."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    type: EventType
    message: str
    timestamp: datetime = Field(default_factory=utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class MissionExecution(BaseModel):
    """Durable worker/dispatch metadata for a mission."""

    state: ExecutionState = ExecutionState.QUEUED
    execution_id: str | None = None
    worker_id: str | None = None
    claimed_at: datetime | None = None
    lease_expires_at: datetime | None = None
    heartbeat_at: datetime | None = None
    attempt_count: int = 0
    max_attempts: int = 3
    last_error: str | None = None

    def is_claimed(self, now: datetime | None = None) -> bool:
        """Whether a worker currently holds a valid lease."""
        if self.state not in {ExecutionState.CLAIMED, ExecutionState.RUNNING}:
            return False
        if self.worker_id is None or self.execution_id is None:
            return False
        current = now or utc_now()
        if self.lease_expires_at is not None and self.lease_expires_at <= current:
            return False
        return True


class MissionExecutionPublic(BaseModel):
    """Safe execution metadata for API responses."""

    state: ExecutionState
    attempt_count: int
    max_attempts: int
    claimed: bool
    worker_id: str | None = None
    execution_id: str | None = None
    lease_expires_at: datetime | None = None
    last_error: str | None = None

    @classmethod
    def from_execution(cls, execution: MissionExecution) -> "MissionExecutionPublic":
        return cls(
            state=execution.state,
            attempt_count=execution.attempt_count,
            max_attempts=execution.max_attempts,
            claimed=execution.is_claimed(),
            worker_id=execution.worker_id if execution.is_claimed() else None,
            execution_id=execution.execution_id if execution.is_claimed() else None,
            lease_expires_at=execution.lease_expires_at,
            last_error=execution.last_error,
        )


class Mission(BaseModel):
    """Core mission aggregate."""

    mission_id: str = Field(default_factory=lambda: str(uuid4()))
    goal: str
    dataset_id: str | None = None
    status: MissionStatus = MissionStatus.CREATED
    current_phase: AgentPhase | None = None
    current_task: str | None = None
    current_objective: str | None = None
    execution_plan: ExecutionPlan | None = None
    agent_plan: AgentPlan | None = None
    delegation_plan: DelegationPlan | None = None
    dataset_profile: DatasetProfile | None = None
    findings: list[Finding] = Field(default_factory=list)
    investigation_report: InvestigationReport | None = None
    tool_invocations: list[ToolInvocation] = Field(default_factory=list)
    evidence_records: list[EvidenceRecord] = Field(default_factory=list)
    interpretations: list[AgentInterpretation] = Field(default_factory=list)
    events: list[MissionEvent] = Field(default_factory=list)
    execution: MissionExecution = Field(default_factory=MissionExecution)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
    completed_at: datetime | None = None
    error: str | None = None

    def touch(self) -> None:
        """Update the updated_at timestamp."""
        self.updated_at = utc_now()


class CreateMissionRequest(BaseModel):
    """Request body for creating a mission."""

    goal: str
    dataset_id: str | None = None
    idempotency_key: str | None = Field(default=None, max_length=128)


class CreateMissionResponse(BaseModel):
    """Immediate response after mission creation."""

    mission_id: str
    status: MissionStatus
    created_at: datetime
    dataset_id: str | None = None


class MissionDetailResponse(BaseModel):
    """Full mission detail response."""

    mission_id: str
    goal: str
    dataset_id: str | None = None
    status: MissionStatus
    current_phase: AgentPhase | None = None
    current_task: str | None = None
    current_objective: str | None = None
    execution_plan: ExecutionPlan | None
    agent_plan: AgentPlan | None = None
    delegation_plan: DelegationPlan | None = None
    investigation_report: InvestigationReport | None = None
    tool_invocations: list[ToolInvocation] = Field(default_factory=list)
    evidence_records: list[EvidenceRecord] = Field(default_factory=list)
    interpretations: list[AgentInterpretation] = Field(default_factory=list)
    events: list[MissionEvent]
    execution: MissionExecutionPublic | None = None
    created_at: datetime
    updated_at: datetime
    completed_at: datetime | None = None
    error: str | None = None

    @classmethod
    def from_mission(cls, mission: Mission) -> "MissionDetailResponse":
        """Build response from domain model."""
        return cls(
            mission_id=mission.mission_id,
            goal=mission.goal,
            dataset_id=mission.dataset_id,
            status=mission.status,
            current_phase=mission.current_phase,
            current_task=mission.current_task,
            current_objective=mission.current_objective,
            execution_plan=mission.execution_plan,
            agent_plan=mission.agent_plan,
            delegation_plan=mission.delegation_plan,
            investigation_report=mission.investigation_report,
            tool_invocations=mission.tool_invocations,
            evidence_records=mission.evidence_records,
            interpretations=mission.interpretations,
            events=mission.events,
            execution=MissionExecutionPublic.from_execution(mission.execution),
            created_at=mission.created_at,
            updated_at=mission.updated_at,
            completed_at=mission.completed_at,
            error=mission.error,
        )


class HealthResponse(BaseModel):
    """Health check response. Never includes secrets."""

    status: str
    app: str
    version: str
    runtime_mode: str
    runtime_role: str
    planner_backend: str
    planner_label: str
    gemini_model: str
    gemini_transport: str
    gemini_meets_minimum: bool
    persistence_backend: str
    storage_backend: str
    dispatcher_backend: str
    adk_configured: bool


DelegationPlan.model_rebuild()
SpecialistTask.model_rebuild()
InvestigationReport.model_rebuild()
Mission.model_rebuild()
MissionDetailResponse.model_rebuild()
