"""Domain models."""

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from atlas.domain.enums import (
    AgentPhase,
    EventType,
    FindingCategory,
    MissionStatus,
    PlannerSource,
    Severity,
    StepStatus,
)


def utc_now() -> datetime:
    """Return current UTC timestamp."""
    return datetime.now(timezone.utc)


class PlanStep(BaseModel):
    """A single step in an execution plan."""

    id: str
    title: str
    description: str
    status: StepStatus = StepStatus.PENDING
    result: str | None = None
    error: str | None = None


class ExecutionPlan(BaseModel):
    """Structured plan generated by the planner."""

    steps: list[PlanStep]
    planner_source: PlannerSource
    summary: str | None = None


class NumericStats(BaseModel):
    """Basic statistics for a numeric column."""

    min: float
    max: float
    mean: float
    median: float
    std: float | None = None


class ColumnProfile(BaseModel):
    """Profile of a single dataset column."""

    name: str
    inferred_type: str
    non_null_count: int
    null_count: int
    null_percent: float
    unique_count: int
    numeric_stats: NumericStats | None = None


class DatasetProfile(BaseModel):
    """Deterministic profile of an inspected CSV."""

    row_count: int
    column_count: int
    columns: list[ColumnProfile]


class Finding(BaseModel):
    """A structured, evidence-based investigation finding."""

    finding_id: str
    category: FindingCategory
    title: str
    description: str
    affected_columns: list[str] = Field(default_factory=list)
    evidence: dict[str, Any] = Field(default_factory=dict)
    affected_row_count: int | None = None
    affected_row_percent: float | None = None
    severity: Severity
    priority: int = 0
    suggested_action: str
    detection_method: str


class RecommendedAction(BaseModel):
    """A recommended remediation action derived from findings."""

    action_id: str
    title: str
    description: str
    related_finding_ids: list[str] = Field(default_factory=list)
    priority: int = 0


class DatasetSummary(BaseModel):
    """Dataset snapshot included in the investigation report."""

    dataset_id: str | None = None
    original_filename: str | None = None
    row_count: int
    column_count: int
    columns: list[ColumnProfile]


class InvestigationReport(BaseModel):
    """Structured final report for a dataset investigation mission."""

    mission_summary: str
    dataset_summary: DatasetSummary
    investigation_summary: str
    findings: list[Finding]
    recommended_actions: list[RecommendedAction]
    overall_assessment: str
    reasoning_source: PlannerSource
    interpretations: list["AgentInterpretation"] = Field(default_factory=list)
    evidence_records: list["EvidenceRecord"] = Field(default_factory=list)


class AgentTask(BaseModel):
    """A single tool-backed task in the agent plan."""

    task_id: str
    tool_name: str
    objective: str
    depends_on: list[str] = Field(default_factory=list)
    status: StepStatus = StepStatus.PENDING
    adaptive: bool = False
    arguments: dict[str, Any] = Field(default_factory=dict)
    evidence_id: str | None = None
    result_summary: str | None = None
    decision_reason: str | None = None


class AgentPlan(BaseModel):
    """Inspectable structured plan of what ATLAS intends to do."""

    objective: str
    source: PlannerSource
    selected_tools: list[str]
    tasks: list[AgentTask] = Field(default_factory=list)
    status: str = "PENDING"
    current_task_id: str | None = None
    iteration: int = 0
    max_iterations: int = 12
    tool_call_count: int = 0

    def to_execution_plan(self) -> ExecutionPlan:
        """Project the agent plan onto the Round 1 execution-plan schema."""
        steps = [
            PlanStep(
                id=task.task_id,
                title=task.tool_name,
                description=task.objective,
                status=task.status,
                result=task.result_summary,
            )
            for task in self.tasks
        ]
        return ExecutionPlan(
            steps=steps,
            planner_source=self.source,
            summary=self.objective,
        )


class ToolInvocation(BaseModel):
    """A recorded tool call for mission observability."""

    invocation_id: str = Field(default_factory=lambda: str(uuid4()))
    tool_name: str
    arguments: dict[str, Any] = Field(default_factory=dict)
    status: StepStatus = StepStatus.PENDING
    evidence_id: str | None = None
    error: str | None = None
    adaptive: bool = False
    started_at: datetime = Field(default_factory=utc_now)
    completed_at: datetime | None = None


class EvidenceRecord(BaseModel):
    """Observed facts produced by a tool. Not agent interpretation."""

    evidence_id: str = Field(default_factory=lambda: str(uuid4()))
    tool_name: str
    task_id: str | None = None
    observed_facts: dict[str, Any] = Field(default_factory=dict)
    finding_ids: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)


class AgentInterpretation(BaseModel):
    """Agent reasoning about measured evidence. Must not invent metrics."""

    interpretation_id: str = Field(default_factory=lambda: str(uuid4()))
    kind: str
    text: str
    related_evidence_ids: list[str] = Field(default_factory=list)
    related_finding_ids: list[str] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)


class DatasetRecord(BaseModel):
    """Persisted metadata for an uploaded dataset."""

    dataset_id: str = Field(default_factory=lambda: str(uuid4()))
    original_filename: str
    stored_filename: str
    content_type: str
    size_bytes: int
    created_at: datetime = Field(default_factory=utc_now)


class DatasetUploadResponse(BaseModel):
    """Response after a successful dataset upload."""

    dataset_id: str
    original_filename: str
    stored_filename: str
    content_type: str
    size_bytes: int
    created_at: datetime

    @classmethod
    def from_record(cls, record: DatasetRecord) -> "DatasetUploadResponse":
        return cls(
            dataset_id=record.dataset_id,
            original_filename=record.original_filename,
            stored_filename=record.stored_filename,
            content_type=record.content_type,
            size_bytes=record.size_bytes,
            created_at=record.created_at,
        )


class MissionEvent(BaseModel):
    """An event recorded during mission execution."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    type: EventType
    message: str
    timestamp: datetime = Field(default_factory=utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class Mission(BaseModel):
    """Core mission aggregate."""

    mission_id: str = Field(default_factory=lambda: str(uuid4()))
    goal: str
    dataset_id: str | None = None
    status: MissionStatus = MissionStatus.CREATED
    current_phase: AgentPhase | None = None
    current_task: str | None = None
    execution_plan: ExecutionPlan | None = None
    agent_plan: AgentPlan | None = None
    investigation_report: InvestigationReport | None = None
    tool_invocations: list[ToolInvocation] = Field(default_factory=list)
    evidence_records: list[EvidenceRecord] = Field(default_factory=list)
    interpretations: list[AgentInterpretation] = Field(default_factory=list)
    events: list[MissionEvent] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
    completed_at: datetime | None = None
    error: str | None = None

    def touch(self) -> None:
        """Update the updated_at timestamp."""
        self.updated_at = utc_now()


class CreateMissionRequest(BaseModel):
    """Request body for creating a mission."""

    goal: str
    dataset_id: str | None = None


class CreateMissionResponse(BaseModel):
    """Immediate response after mission creation."""

    mission_id: str
    status: MissionStatus
    created_at: datetime
    dataset_id: str | None = None


class MissionDetailResponse(BaseModel):
    """Full mission detail response."""

    mission_id: str
    goal: str
    dataset_id: str | None = None
    status: MissionStatus
    current_phase: AgentPhase | None = None
    current_task: str | None = None
    execution_plan: ExecutionPlan | None
    agent_plan: AgentPlan | None = None
    investigation_report: InvestigationReport | None = None
    tool_invocations: list[ToolInvocation] = Field(default_factory=list)
    evidence_records: list[EvidenceRecord] = Field(default_factory=list)
    interpretations: list[AgentInterpretation] = Field(default_factory=list)
    events: list[MissionEvent]
    created_at: datetime
    updated_at: datetime
    completed_at: datetime | None = None
    error: str | None = None

    @classmethod
    def from_mission(cls, mission: Mission) -> "MissionDetailResponse":
        """Build response from domain model."""
        return cls(
            mission_id=mission.mission_id,
            goal=mission.goal,
            dataset_id=mission.dataset_id,
            status=mission.status,
            current_phase=mission.current_phase,
            current_task=mission.current_task,
            execution_plan=mission.execution_plan,
            agent_plan=mission.agent_plan,
            investigation_report=mission.investigation_report,
            tool_invocations=mission.tool_invocations,
            evidence_records=mission.evidence_records,
            interpretations=mission.interpretations,
            events=mission.events,
            created_at=mission.created_at,
            updated_at=mission.updated_at,
            completed_at=mission.completed_at,
            error=mission.error,
        )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    app: str
    version: str
    planner_backend: str
    adk_configured: bool


InvestigationReport.model_rebuild()
Mission.model_rebuild()
MissionDetailResponse.model_rebuild()
