"""Domain models."""

from datetime import datetime, timezone
from typing import Any
from uuid import uuid4

from pydantic import BaseModel, Field

from atlas.domain.enums import (
    EventType,
    MissionStatus,
    PlannerSource,
    StepStatus,
)


def utc_now() -> datetime:
    """Return current UTC timestamp."""
    return datetime.now(timezone.utc)


class PlanStep(BaseModel):
    """A single step in an execution plan."""

    id: str
    title: str
    description: str
    status: StepStatus = StepStatus.PENDING
    result: str | None = None
    error: str | None = None


class ExecutionPlan(BaseModel):
    """Structured plan generated by the planner."""

    steps: list[PlanStep]
    planner_source: PlannerSource
    summary: str | None = None


class MissionEvent(BaseModel):
    """An event recorded during mission execution."""

    id: str = Field(default_factory=lambda: str(uuid4()))
    type: EventType
    message: str
    timestamp: datetime = Field(default_factory=utc_now)
    metadata: dict[str, Any] = Field(default_factory=dict)


class Mission(BaseModel):
    """Core mission aggregate."""

    mission_id: str = Field(default_factory=lambda: str(uuid4()))
    goal: str
    status: MissionStatus = MissionStatus.CREATED
    execution_plan: ExecutionPlan | None = None
    events: list[MissionEvent] = Field(default_factory=list)
    created_at: datetime = Field(default_factory=utc_now)
    updated_at: datetime = Field(default_factory=utc_now)
    completed_at: datetime | None = None
    error: str | None = None

    def touch(self) -> None:
        """Update the updated_at timestamp."""
        self.updated_at = utc_now()


class CreateMissionRequest(BaseModel):
    """Request body for creating a mission."""

    goal: str


class CreateMissionResponse(BaseModel):
    """Immediate response after mission creation."""

    mission_id: str
    status: MissionStatus
    created_at: datetime


class MissionDetailResponse(BaseModel):
    """Full mission detail response."""

    mission_id: str
    goal: str
    status: MissionStatus
    execution_plan: ExecutionPlan | None
    events: list[MissionEvent]
    created_at: datetime
    updated_at: datetime
    completed_at: datetime | None = None
    error: str | None = None

    @classmethod
    def from_mission(cls, mission: Mission) -> "MissionDetailResponse":
        """Build response from domain model."""
        return cls(
            mission_id=mission.mission_id,
            goal=mission.goal,
            status=mission.status,
            execution_plan=mission.execution_plan,
            events=mission.events,
            created_at=mission.created_at,
            updated_at=mission.updated_at,
            completed_at=mission.completed_at,
            error=mission.error,
        )


class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    app: str
    version: str
    planner_backend: str
    adk_configured: bool
